# Generated by Django 3.2 on 2022-08-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('online', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('date', models.DateField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
