# Generated by Django 3.2 on 2022-08-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('daily_sale.daily_sale',),
        ),
    ]
