# Generated by Django 3.2 on 2022-08-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_sale', '0002_salesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleSummary',
        ),
    ]
